#############################################################################
# Makefile for building: bin/ddplot
# Generated by qmake (2.01a) (Qt 4.5.2) on: Tue Dec 7 08:17:38 2010
# Project:  ddplot.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -unix -o Makefile ddplot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -Isrc
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = src/

####### Files

SOURCES       = src/animate.cpp \
		src/atomstyle.cpp \
		src/ddplot.cpp \
		src/fformat.cpp \
		src/messages.cpp \
		src/appwin.cpp \
		src/appwin-func.cpp \
		src/misc.cpp \
		src/neighlist.cpp \
		src/pltwin.cpp \
		src/pltwin-calc.cpp \
		src/pltwin-geom.cpp \
		src/pltwin-func.cpp \
		src/rdf.cpp \
		src/scalepos.cpp \
		src/selectplots.cpp \
		src/selectzlayers.cpp \
		src/strings.cpp \
		src/calcs.cpp \
		src/cline.cpp \
		src/darray.cpp src/moc_animate.cpp \
		src/moc_atomstyle.cpp \
		src/moc_appwin.cpp \
		src/moc_pltwin.cpp \
		src/moc_scalepos.cpp \
		src/moc_selectplots.cpp \
		src/moc_selectzlayers.cpp \
		src/qrc_ddplot.cpp
OBJECTS       = src/animate.o \
		src/atomstyle.o \
		src/ddplot.o \
		src/fformat.o \
		src/messages.o \
		src/appwin.o \
		src/appwin-func.o \
		src/misc.o \
		src/neighlist.o \
		src/pltwin.o \
		src/pltwin-calc.o \
		src/pltwin-geom.o \
		src/pltwin-func.o \
		src/rdf.o \
		src/scalepos.o \
		src/selectplots.o \
		src/selectzlayers.o \
		src/strings.o \
		src/calcs.o \
		src/cline.o \
		src/darray.o \
		src/moc_animate.o \
		src/moc_atomstyle.o \
		src/moc_appwin.o \
		src/moc_pltwin.o \
		src/moc_scalepos.o \
		src/moc_selectplots.o \
		src/moc_selectzlayers.o \
		src/qrc_ddplot.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		ddplot.pro
QMAKE_TARGET  = ddplot
DESTDIR       = bin/
TARGET        = bin/ddplot

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): src/ui_dabout.h src/ui_dburgvect.h src/ui_dprojvector.h src/ui_dscalearrow.h src/ui_datomstyle.h src/ui_darrowstyle.h src/ui_dselectplots.h src/ui_danimate.h src/ui_dshowplanes.h src/ui_darrneighbors.h src/ui_dcoordsys.h src/ui_dtransform.h src/ui_drelaxinfo.h src/ui_dscalepos.h src/ui_dselectzlayers.h src/ui_dnewcutoff.h src/ui_dcomparedisp.h src/ui_dcoordatoms.h src/ui_dztolerance.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ddplot.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_off.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile ddplot.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_off.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile ddplot.pro

dist: 
	@$(CHK_DIR_EXISTS) src/ddplot1.0.0 || $(MKDIR) src/ddplot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) src/ddplot1.0.0/ && $(COPY_FILE) --parents src/animate.h src/atomstyle.h src/ddplot.h src/fformat.h src/messages.h src/appwin.h src/misc.h src/neighlist.h src/pltwin.h src/rdf.h src/scalepos.h src/selectplots.h src/selectzlayers.h src/strings.h src/calcs.h src/cline.h src/darray.h src/ddplot1.0.0/ && $(COPY_FILE) --parents ddplot.qrc src/ddplot1.0.0/ && $(COPY_FILE) --parents src/animate.cpp src/atomstyle.cpp src/ddplot.cpp src/fformat.cpp src/messages.cpp src/appwin.cpp src/appwin-func.cpp src/misc.cpp src/neighlist.cpp src/pltwin.cpp src/pltwin-calc.cpp src/pltwin-geom.cpp src/pltwin-func.cpp src/rdf.cpp src/scalepos.cpp src/selectplots.cpp src/selectzlayers.cpp src/strings.cpp src/calcs.cpp src/cline.cpp src/darray.cpp src/ddplot1.0.0/ && $(COPY_FILE) --parents ui/dabout.ui ui/dburgvect.ui ui/dprojvector.ui ui/dscalearrow.ui ui/datomstyle.ui ui/darrowstyle.ui ui/dselectplots.ui ui/danimate.ui ui/dshowplanes.ui ui/darrneighbors.ui ui/dcoordsys.ui ui/dtransform.ui ui/drelaxinfo.ui ui/dscalepos.ui ui/dselectzlayers.ui ui/dnewcutoff.ui ui/dcomparedisp.ui ui/dcoordatoms.ui ui/dztolerance.ui src/ddplot1.0.0/ && (cd `dirname src/ddplot1.0.0` && $(TAR) ddplot1.0.0.tar ddplot1.0.0 && $(COMPRESS) ddplot1.0.0.tar) && $(MOVE) `dirname src/ddplot1.0.0`/ddplot1.0.0.tar.gz . && $(DEL_FILE) -r src/ddplot1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: src/moc_animate.cpp src/moc_atomstyle.cpp src/moc_appwin.cpp src/moc_pltwin.cpp src/moc_scalepos.cpp src/moc_selectplots.cpp src/moc_selectzlayers.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) src/moc_animate.cpp src/moc_atomstyle.cpp src/moc_appwin.cpp src/moc_pltwin.cpp src/moc_scalepos.cpp src/moc_selectplots.cpp src/moc_selectzlayers.cpp
src/moc_animate.cpp: src/ui_danimate.h \
		src/animate.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/animate.h -o src/moc_animate.cpp

src/moc_atomstyle.cpp: src/darray.h \
		src/pltwin.h \
		src/ddplot.h \
		src/ui_datomstyle.h \
		src/atomstyle.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/atomstyle.h -o src/moc_atomstyle.cpp

src/moc_appwin.cpp: src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/strings.h \
		src/appwin.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/appwin.h -o src/moc_appwin.cpp

src/moc_pltwin.cpp: src/ddplot.h \
		src/darray.h \
		src/pltwin.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/pltwin.h -o src/moc_pltwin.cpp

src/moc_scalepos.cpp: src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/ui_dscalepos.h \
		src/scalepos.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/scalepos.h -o src/moc_scalepos.cpp

src/moc_selectplots.cpp: src/ui_dselectplots.h \
		src/selectplots.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/selectplots.h -o src/moc_selectplots.cpp

src/moc_selectzlayers.cpp: src/ui_dselectzlayers.h \
		src/selectzlayers.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/selectzlayers.h -o src/moc_selectzlayers.cpp

compiler_rcc_make_all: src/qrc_ddplot.cpp
compiler_rcc_clean:
	-$(DEL_FILE) src/qrc_ddplot.cpp
src/qrc_ddplot.cpp: ddplot.qrc \
		ico/ddplot.png \
		ico/ddplot.icns
	/usr/bin/rcc -name ddplot ddplot.qrc -o src/qrc_ddplot.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: src/ui_dabout.h src/ui_dburgvect.h src/ui_dprojvector.h src/ui_dscalearrow.h src/ui_datomstyle.h src/ui_darrowstyle.h src/ui_dselectplots.h src/ui_danimate.h src/ui_dshowplanes.h src/ui_darrneighbors.h src/ui_dcoordsys.h src/ui_dtransform.h src/ui_drelaxinfo.h src/ui_dscalepos.h src/ui_dselectzlayers.h src/ui_dnewcutoff.h src/ui_dcomparedisp.h src/ui_dcoordatoms.h src/ui_dztolerance.h
compiler_uic_clean:
	-$(DEL_FILE) src/ui_dabout.h src/ui_dburgvect.h src/ui_dprojvector.h src/ui_dscalearrow.h src/ui_datomstyle.h src/ui_darrowstyle.h src/ui_dselectplots.h src/ui_danimate.h src/ui_dshowplanes.h src/ui_darrneighbors.h src/ui_dcoordsys.h src/ui_dtransform.h src/ui_drelaxinfo.h src/ui_dscalepos.h src/ui_dselectzlayers.h src/ui_dnewcutoff.h src/ui_dcomparedisp.h src/ui_dcoordatoms.h src/ui_dztolerance.h
src/ui_dabout.h: ui/dabout.ui
	/usr/bin/uic-qt4 ui/dabout.ui -o src/ui_dabout.h

src/ui_dburgvect.h: ui/dburgvect.ui
	/usr/bin/uic-qt4 ui/dburgvect.ui -o src/ui_dburgvect.h

src/ui_dprojvector.h: ui/dprojvector.ui
	/usr/bin/uic-qt4 ui/dprojvector.ui -o src/ui_dprojvector.h

src/ui_dscalearrow.h: ui/dscalearrow.ui
	/usr/bin/uic-qt4 ui/dscalearrow.ui -o src/ui_dscalearrow.h

src/ui_datomstyle.h: ui/datomstyle.ui
	/usr/bin/uic-qt4 ui/datomstyle.ui -o src/ui_datomstyle.h

src/ui_darrowstyle.h: ui/darrowstyle.ui
	/usr/bin/uic-qt4 ui/darrowstyle.ui -o src/ui_darrowstyle.h

src/ui_dselectplots.h: ui/dselectplots.ui
	/usr/bin/uic-qt4 ui/dselectplots.ui -o src/ui_dselectplots.h

src/ui_danimate.h: ui/danimate.ui
	/usr/bin/uic-qt4 ui/danimate.ui -o src/ui_danimate.h

src/ui_dshowplanes.h: ui/dshowplanes.ui
	/usr/bin/uic-qt4 ui/dshowplanes.ui -o src/ui_dshowplanes.h

src/ui_darrneighbors.h: ui/darrneighbors.ui
	/usr/bin/uic-qt4 ui/darrneighbors.ui -o src/ui_darrneighbors.h

src/ui_dcoordsys.h: ui/dcoordsys.ui
	/usr/bin/uic-qt4 ui/dcoordsys.ui -o src/ui_dcoordsys.h

src/ui_dtransform.h: ui/dtransform.ui
	/usr/bin/uic-qt4 ui/dtransform.ui -o src/ui_dtransform.h

src/ui_drelaxinfo.h: ui/drelaxinfo.ui
	/usr/bin/uic-qt4 ui/drelaxinfo.ui -o src/ui_drelaxinfo.h

src/ui_dscalepos.h: ui/dscalepos.ui
	/usr/bin/uic-qt4 ui/dscalepos.ui -o src/ui_dscalepos.h

src/ui_dselectzlayers.h: ui/dselectzlayers.ui
	/usr/bin/uic-qt4 ui/dselectzlayers.ui -o src/ui_dselectzlayers.h

src/ui_dnewcutoff.h: ui/dnewcutoff.ui
	/usr/bin/uic-qt4 ui/dnewcutoff.ui -o src/ui_dnewcutoff.h

src/ui_dcomparedisp.h: ui/dcomparedisp.ui
	/usr/bin/uic-qt4 ui/dcomparedisp.ui -o src/ui_dcomparedisp.h

src/ui_dcoordatoms.h: ui/dcoordatoms.ui
	/usr/bin/uic-qt4 ui/dcoordatoms.ui -o src/ui_dcoordatoms.h

src/ui_dztolerance.h: ui/dztolerance.ui
	/usr/bin/uic-qt4 ui/dztolerance.ui -o src/ui_dztolerance.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

src/animate.o: src/animate.cpp src/animate.h \
		src/ui_danimate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/animate.o src/animate.cpp

src/atomstyle.o: src/atomstyle.cpp src/atomstyle.h \
		src/darray.h \
		src/pltwin.h \
		src/ddplot.h \
		src/ui_datomstyle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/atomstyle.o src/atomstyle.cpp

src/ddplot.o: src/ddplot.cpp src/appwin.h \
		src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/strings.h \
		src/cline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/ddplot.o src/ddplot.cpp

src/fformat.o: src/fformat.cpp src/ddplot.h \
		src/fformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/fformat.o src/fformat.cpp

src/messages.o: src/messages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/messages.o src/messages.cpp

src/appwin.o: src/appwin.cpp xpm/fileopen.xpm \
		xpm/filesave.xpm \
		xpm/fileprint.xpm \
		src/appwin.h \
		src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/appwin.o src/appwin.cpp

src/appwin-func.o: src/appwin-func.cpp src/ui_dabout.h \
		src/ui_danimate.h \
		src/ui_darrneighbors.h \
		src/ui_darrowstyle.h \
		src/ui_datomstyle.h \
		src/ui_dburgvect.h \
		src/ui_dcomparedisp.h \
		src/ui_dcoordatoms.h \
		src/ui_dcoordsys.h \
		src/ui_dprojvector.h \
		src/ui_dscalearrow.h \
		src/ui_dselectplots.h \
		src/ui_dselectzlayers.h \
		src/ui_drelaxinfo.h \
		src/ui_dscalepos.h \
		src/ui_dshowplanes.h \
		src/ui_dtransform.h \
		src/ui_dztolerance.h \
		src/appwin.h \
		src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/strings.h \
		src/animate.h \
		src/atomstyle.h \
		src/calcs.h \
		src/fformat.h \
		src/messages.h \
		src/misc.h \
		src/neighlist.h \
		src/scalepos.h \
		src/selectplots.h \
		src/selectzlayers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/appwin-func.o src/appwin-func.cpp

src/misc.o: src/misc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/misc.o src/misc.cpp

src/neighlist.o: src/neighlist.cpp src/ddplot.h \
		src/messages.h \
		src/neighlist.h \
		src/pltwin.h \
		src/darray.h \
		src/rdf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/neighlist.o src/neighlist.cpp

src/pltwin.o: src/pltwin.cpp src/appwin.h \
		src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/strings.h \
		src/calcs.h \
		src/messages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/pltwin.o src/pltwin.cpp

src/pltwin-calc.o: src/pltwin-calc.cpp src/neighlist.h \
		src/pltwin.h \
		src/ddplot.h \
		src/darray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/pltwin-calc.o src/pltwin-calc.cpp

src/pltwin-geom.o: src/pltwin-geom.cpp src/pltwin.h \
		src/ddplot.h \
		src/darray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/pltwin-geom.o src/pltwin-geom.cpp

src/pltwin-func.o: src/pltwin-func.cpp src/ui_dnewcutoff.h \
		src/calcs.h \
		src/darray.h \
		src/messages.h \
		src/misc.h \
		src/neighlist.h \
		src/pltwin.h \
		src/ddplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/pltwin-func.o src/pltwin-func.cpp

src/rdf.o: src/rdf.cpp src/ddplot.h \
		src/messages.h \
		src/neighlist.h \
		src/pltwin.h \
		src/darray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/rdf.o src/rdf.cpp

src/scalepos.o: src/scalepos.cpp src/scalepos.h \
		src/pltwin.h \
		src/ddplot.h \
		src/darray.h \
		src/ui_dscalepos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/scalepos.o src/scalepos.cpp

src/selectplots.o: src/selectplots.cpp src/selectplots.h \
		src/ui_dselectplots.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/selectplots.o src/selectplots.cpp

src/selectzlayers.o: src/selectzlayers.cpp src/selectzlayers.h \
		src/ui_dselectzlayers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/selectzlayers.o src/selectzlayers.cpp

src/strings.o: src/strings.cpp src/strings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/strings.o src/strings.cpp

src/calcs.o: src/calcs.cpp src/darray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/calcs.o src/calcs.cpp

src/cline.o: src/cline.cpp src/cline.h \
		src/ddplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/cline.o src/cline.cpp

src/darray.o: src/darray.cpp src/darray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/darray.o src/darray.cpp

src/moc_animate.o: src/moc_animate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_animate.o src/moc_animate.cpp

src/moc_atomstyle.o: src/moc_atomstyle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_atomstyle.o src/moc_atomstyle.cpp

src/moc_appwin.o: src/moc_appwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_appwin.o src/moc_appwin.cpp

src/moc_pltwin.o: src/moc_pltwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_pltwin.o src/moc_pltwin.cpp

src/moc_scalepos.o: src/moc_scalepos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_scalepos.o src/moc_scalepos.cpp

src/moc_selectplots.o: src/moc_selectplots.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_selectplots.o src/moc_selectplots.cpp

src/moc_selectzlayers.o: src/moc_selectzlayers.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/moc_selectzlayers.o src/moc_selectzlayers.cpp

src/qrc_ddplot.o: src/qrc_ddplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o src/qrc_ddplot.o src/qrc_ddplot.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

